config/routes.rb
Rails.application.routes.draw do
  resources :techniques
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  acts_as_list scope: :recipe_id

  searchkick
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, -> { order(position: :asc) }, dependent: :destroy
  has_and_belongs_to_many :techniques

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  has_many :steps, -> { order(position: :asc) }, dependent: :destroy
  accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true

  searchkick
  scope :search_import, -> { includes(:ingredients, :techniques, :steps) }

  def search_data
    {
      ingredients: ingredients.map(&:name),
      techniques: techniques.map(&:name),
      steps: steps.map(&:body)
    }
  end

  LANGUAGES = %w(en fr).freeze
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
  acts_as_list scope: :recipe_id
end

app/models/technique.rb
class Technique < ApplicationRecord
  has_and_belongs_to_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all.order(:difficulty)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
    @recipe.steps.build
  end

  # GET /recipes/1/edit
  def edit
    @recipe.ingredients.build if @recipe.ingredients.empty?
    @recipe.steps.build if @recipe.steps.empty?
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy!

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(
        :name,
        :notes,
        :difficulty,
        :language,
        ingredients_attributes: [
          :id,
          :position,
          :_destroy,
          :name,
          :quantity,
          :unit
        ],
        steps_attributes: [
          :id,
          :body,
          :position,
          :_destroy
        ],
        technique_ids: []
      )
    end
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  before_action :set_technique, only: %i[ show edit update destroy ]

  # GET /techniques or /techniques.json
  def index
    @techniques = Technique.all
  end

  # GET /techniques/1 or /techniques/1.json
  def show
  end

  # GET /techniques/new
  def new
    @technique = Technique.new
  end

  # GET /techniques/1/edit
  def edit
  end

  # POST /techniques or /techniques.json
  def create
    @technique = Technique.new(technique_params)

    respond_to do |format|
      if @technique.save
        format.html { redirect_to technique_url(@technique), notice: "Technique was successfully created." }
        format.json { render :show, status: :created, location: @technique }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @technique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /techniques/1 or /techniques/1.json
  def update
    respond_to do |format|
      if @technique.update(technique_params)
        format.html { redirect_to technique_url(@technique), notice: "Technique was successfully updated." }
        format.json { render :show, status: :ok, location: @technique }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @technique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /techniques/1 or /techniques/1.json
  def destroy
    @technique.destroy!

    respond_to do |format|
      format.html { redirect_to techniques_url, notice: "Technique was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technique
      @technique = Technique.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def technique_params
      params.require(:technique).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
  def units
    [nil, "ml", "g"]
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalaisonApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-slate-50 m-10 p-20">
    <div class="w-full max-w-5xl m-1 p-3 mx-auto bg-white shadow-lg rounded-lg">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4") do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :name, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <fieldset class="m-4" data-controller="growing_list">
    <legend class="block text-gray-700 font-bold mb-2">Ingredients</legend>

    <ul data-controller="drag">
      <%= form.fields_for :ingredients do |ingredient_fields| %>
        <li>
          <div class="flex mb-4">
            <%= ingredient_fields.hidden_field :_destroy %>
            <%= ingredient_fields.hidden_field :position %>
            <div class="flex items-center justify-center p-1 cursor-grab">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
            </div>
            <div class="pr-2 flex-grow">
              <%= ingredient_fields.text_field :name, placeholder: 'Name', class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
            </div>
            <div class="pl-2 pr-2">
              <%= ingredient_fields.number_field :quantity, placeholder: "Quantity", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
            </div>
            <div class="pl-2 pr-2">
              <%= ingredient_fields.select :unit, options_for_select(units, ingredient_fields.object.unit), {}, { class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" } %>
            </div>
            <div class="pl-2">
              <button type="button" data-action="click->growing_list#removeListItem" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
</svg>
              </button>
            </div>
          </div>
        </li>
      <% end %>
      <li>
        <button type="button" data-action="click->growing_list#addListItem" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </button>
      </li>
    </ul>
  </fieldset>

  <fieldset class="m-4" data-controller="growing_list">
    <legend class="block text-gray-700 font-bold mb-2">Steps</legend>

    <ol data-controller="drag">
      <%= form.fields_for :steps do |step_fields| %>
        <li>
          <div class="flex mb-4">
            <%= step_fields.hidden_field :_destroy %>
            <%= step_fields.hidden_field :position %>
            <div class="flex items-center justify-center p-1 cursor-grab">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
            </div>
            <div class="pr-2 flex-grow">
              <%= step_fields.text_area :body, placeholder: 'Body', class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
            </div>
            <div class="w-1/4 pl-2">
              <button type="button" data-action="click->growing_list#removeListItem" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </button>
            </div>
          </div>
        </li>
      <% end %>
      <li>
        <button type="button" data-action="click->growing_list#addListItem" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </button>
      </li>
    </ol>
  </fieldset>

  <div class="mb-4">
    <%= form.label :notes, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_area :notes, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :difficulty, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.select :difficulty, options_for_select([['⚡', 1], ['⚡⚡', 2], ['⚡⚡⚡', 3]], recipe.difficulty), {}, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>

  <%= form.hidden_field :language, value: 'fr' %>

  <div class="mb-4">
    <ul>
      <%= form.collection_check_boxes(:technique_ids, Technique.all, :id, :name) do |b| %>
        <li>
          <label class="your-label-class">
            <%= b.check_box(class: "mx-4") %>
            <%= b.label %>
          </label>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit "Save Recipe", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="m-10">
  <h1 class="text-4xl font-bold" title="<%= recipe.name %> (<%= recipe.language %>)">
    <%= recipe.name %>
  </h1>

  <div class="p-3 flex">
    <% recipe.techniques.each do |technique| %>
      <div class="rounded-full shadow mr-2 px-2 text-xs bg-yellow-100">
        <%= technique.name %>
      </div>
    <% end %>
  </div>

  <div class="p-3 flex">
    <% (recipe.difficulty || 1).times do  %>
      <div class="mr-2">
        ⚡
      </div>
    <% end %>
  </div>

  <div class="flex flex-row items-center border-b-2 p-3 pb-2">
    <div class="grow-0">
      <ul class="pr-4">
        <% recipe.ingredients.each do |ingredient| %>
          <li><%= ingredient.name %></li>
        <% end %>
      </ul>
    </div>
    <div class="">
      <ul>
        <% recipe.ingredients.each do |ingredient| %>
          <li class="text-right"><%= ingredient.quantity %><%= ingredient.unit %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="p-3">
    <ol class="list-decimal">
      <% recipe.steps.each do |step| %>
        <li><%= step.body %></li>
      <% end %>
    </ol>
  </div>

  <div class="flex p-3">
    <div class="">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
      </svg>
    </div>
    <div class="flex-grow"><%= simple_format(recipe.notes, class: "pb-4") %></div>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1 class="text-3xl font-bold mb-4">Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<div class="mt-8">
  <%= link_to "Show this recipe", @recipe, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-4" %>
  <%= link_to "Back to recipes", recipes_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>
</div>

app/views/recipes/index.html.erb
<p class="text-green-500"><%= notice %></p>

<div class="flex">
  <div class="flex-grow">
    <h1 class="text-5xl font-bold mb-4">Recipes</h1>
  </div>
  <div class="m-4">
    <%= link_to "New recipe", new_recipe_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mt-10" %>
  </div>
</div>

<div id="recipes" class="">
  <% if @recipes.empty? %>
    <p class="p-5">No recipes yet.</p>
  <% end %>

  <% difficulty = 0 %>
  <% @recipes.each do |recipe| %>
    <% if recipe.difficulty != difficulty %>
      <% difficulty = recipe.difficulty %>
      <h2 class="text-2xl font-bold mb-4 mt-10 text-center rounded-full bg-slate-100"><%= ["Facile", "Intermediaire", "Difficile"][difficulty - 1] %></h2>
    <% end %>

    <%= link_to recipe, class: "block rounded hover:shadow p-2" do %>
      <div class="flex items-center">
        <div class="flex-grow">
          <h2 class="text-2xl font-bold mb-2">
            <%= recipe.name %>
            <% recipe.techniques.each do |technique| %>
              <span class="rounded-full shadow mr-2 px-2 text-xs bg-yellow-100">
                <%= technique.name %>
              </span>
            <% end %>
          </h2>
          <p class="text-xs mb-4"><%= recipe.ingredients.map(&:name).join(", ") %></p>
        </div>
        <div class="flex justify-end">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" /></svg>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1 class="text-4xl font-bold">New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path, class: "text-blue-500 hover:text-blue-700" %>
</div>

app/views/recipes/show.html.erb
<%= link_to recipes_path, class: "text-blue-500 hover:text-blue-700" do %>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
  </svg>
<% end %>

<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div class="flex justify-end">
  <div class="mr-10">
    <%= link_to edit_recipe_path(@recipe), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" do %>
      Edit
    <% end %>
  </div>
  <div>
    <%= link_to 'Delete', recipe_path(@recipe), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "text-red-500 hover:text-red-600" %>
  </div>
</div>

app/views/techniques/_form.html.erb
<%= form_with(model: technique, html: { class: "bg-gray-100 p-4 rounded-lg" }) do |form| %>
  <% if technique.errors.any? %>
    <div style="color: red" class="mb-4">
      <h2 class="text-red-500"><%= pluralize(technique.errors.count, "error") %> prohibited this technique from being saved:</h2>

      <ul>
        <% technique.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :name, style: "display: block", class: "text-gray-700 font-bold" %>
    <%= form.text_field :name, class: "border border-gray-300 rounded-lg p-2 w-full" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, style: "display: block", class: "text-gray-700 font-bold" %>
    <%= form.text_area :description, class: "border border-gray-300 rounded-lg p-2 w-full" %>
  </div>

  <div>
    <%= form.submit "Save", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
<% end %>

app/views/techniques/_technique.html.erb
<div id="<%= dom_id technique %>">
  <p>
    <strong>Name:</strong>
    <%= technique.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= technique.description %>
  </p>

</div>

app/views/techniques/edit.html.erb
<h1>Editing technique</h1>

<%= render "form", technique: @technique %>

<br>

<div>
  <%= link_to "Show this technique", @technique %> |
  <%= link_to "Back to techniques", techniques_path %>
</div>

app/views/techniques/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Techniques</h1>

<div id="techniques">
  <% @techniques.each do |technique| %>
    <%= render technique %>
    <p>
      <%= link_to "Show this technique", technique %>
    </p>
  <% end %>
</div>

<%= link_to "New technique", new_technique_path %>

app/views/techniques/new.html.erb
<h1>New technique</h1>

<%= render "form", technique: @technique %>

<br>

<div>
  <%= link_to "Back to techniques", techniques_path %>
</div>

app/views/techniques/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @technique %>

<div>
  <%= link_to "Edit this technique", edit_technique_path(@technique) %> |
  <%= link_to "Back to techniques", techniques_path %>

  <%= button_to "Destroy this technique", @technique, method: :delete %>
</div>